---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hypershiftlogforwarder.managed.openshift.io.managed.openshift.io
  resources:
  - hypershiftlogforwarders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hypershiftlogforwarder.managed.openshift.io.managed.openshift.io
  resources:
  - hypershiftlogforwarders/finalizers
  verbs:
  - update
- apiGroups:
  - hypershiftlogforwarder.managed.openshift.io.managed.openshift.io
  resources:
  - hypershiftlogforwarders/status
  verbs:
  - get
  - patch
  - update
